class CustomError(Exception):
    def custom_exception(Exception):
        print(Exception)